USE sakila;

-- Challenge - Joining on multiple tables
-- Write SQL queries to perform the following tasks using the Sakila database:

-- 1. List the number of films per category.
SELECT c.name AS category_name, COUNT(f.film_id) AS number_of_films
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
GROUP BY c.name;

SELECT category.name AS category_name,
	(SELECT COUNT(*)
    FROM film_category
    WHERE film_category.category_if = category.category_id) AS number_of_films
FROM category;    

-- 2. Retrieve the store ID, city, and country for each store.
SELECT * FROM store;
SELECT * FROM address;
SELECT * FROM country;
SELECT * FROM city; 

SELECT s.store_id, ci.city, co.country
FROM store s
JOIN address a ON s.address_id = a.address_id
JOIN city ci ON a.city_id = ci.city_id
JOIN country co ON ci.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.

SELECT * FROM payment;

SELECT s.store_id as store,
CONCAT('$', FORMAT(SUM(p.amount), 2)) AS total_revenue
FROM payment as p
JOIN staff as st
ON st.staff_id = p.staff_id
JOIN store as s
ON s.store_id = st.store_id
GROUP BY store;    

-- 4. Determine the average running time of films for each category.

SELECT * FROM film;
SELECT * FROM category;

SELECT c.name AS category_name, ROUND(AVG(length),0) AS average_film_duration
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
GROUP BY c.name;



